version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
